package com.bippobippo.hospital.repository.channel;

import com.bippobippo.hospital.entity.channel.Channel;
import com.bippobippo.hospital.entity.channel.ChannelApprovalStatus;
import com.bippobippo.hospital.entity.channel.ChannelSourceType;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ChannelRepository extends JpaRepository<Channel, Long> {
    List<Channel> findByIsActiveTrue();
    List<Channel> findByIsAutoGeneratedTrue();
    List<Channel> findBySourceType(ChannelSourceType sourceType);
    List<Channel> findByApprovalStatus(ChannelApprovalStatus status);
} 