server:
  port: 3002
  servlet:
    context-path: /
  tomcat:
    max-threads: 200
    min-spare-threads: 10
    max-connections: 10000
    accept-count: 100
    connection-timeout: 20000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hospital_dev?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: hospital_dev
    password: new_dev_password_123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    enabled: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        validate_schema: false
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: hospital
  data:
    mongodb:
      uri: mongodb://localhost:27017/hospital_dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: bippobippo119@gmail.com
    password: bswp vdvq gbsj nszg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    root: INFO
    com.bippobippo.hospital: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.data.mongodb: DEBUG
    org.mongodb.driver: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO

jwt:
  secret: 8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb
  expiration: 86400000 # 24시간

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

security:
  user:
    name: admin
    password: admin

gcs:
  bucket:
    name: your-bucket-name
  credentials:
    location: classpath:gcs-credentials.json

elasticsearch:
  host: localhost
  port: 9200
  url: ${ELASTICSEARCH_URL:http://localhost:9200}

openai:
  api:
    key: ${OPENAI_API_KEY:your-api-key-here}

# 버스 API 설정
bus:
  api:
    serviceKey: ${BUS_API_SERVICE_KEY:your-bus-api-key-here}
    cities: ${BUS_API_CITIES:seoul,busan,daegu}

# API 호출 제한 관리 설정
api:
  rate-limit:
    batch-size: 5                    # 한 번에 처리할 노선 수
    delay-between-batches: 3000      # 배치 간 대기 시간 (밀리초)
    delay-after-rate-limit: 15000    # 호출 제한 후 대기 시간 (밀리초)
    max-rate-limit-retries: 3        # 최대 재시도 횟수
    delay-between-requests: 200      # 요청 간 대기 시간 (밀리초)
    max-rate-limit-count: 3          # 최대 호출 제한 발생 횟수
    extended-wait-time: 60000        # 연속 호출 제한 시 대기 시간 (밀리초)

# 로컬 파일 업로드 설정
app:
  upload:
    path: src/main/resources/static/uploads 