package com.bippobippo.hospital.entity.channel;

import javax.persistence.*;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;

@Entity
@Table(name = "hospital_channels")
@Getter
@Setter
public class Channel {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String name;

    @Column(length = 1000)
    private String description;

    @Column(name = "image_url")
    private String imageUrl;

    @Column(name = "channel_uri")
    private String channelUri;

    @Column(name = "follower_count")
    private Integer followerCount = 0;

    @Column(name = "is_auto_generated")
    private Boolean isAutoGenerated = false;

    @Column(name = "source_type")
    @Enumerated(EnumType.STRING)
    private ChannelSourceType sourceType;

    @Column(name = "approval_status")
    @Enumerated(EnumType.STRING)
    private ChannelApprovalStatus approvalStatus = ChannelApprovalStatus.PENDING;

    @Column(name = "rejection_reason")
    private String rejectionReason;

    @Column(name = "last_updated")
    @UpdateTimestamp
    private LocalDateTime lastUpdated;

    @Column(name = "created_at")
    @CreationTimestamp
    private LocalDateTime createdAt;

    @Column(name = "is_active")
    private Boolean isActive = true;

    @Column(name = "type", nullable = false)
    @Enumerated(EnumType.STRING)
    private ChannelType type = ChannelType.CHANNEL;
} 