apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-restore-job
spec:
  template:
    spec:
      containers:
      - name: mongo-restore
        image: mongo:latest
        # 아래 명령은 복원 작업을 예시로 보여줍니다.
        # 실제 환경에 맞게 커맨드와 인자를 수정하세요.
        command: ["sh", "-c", "mongorestore --host mongodb-service --port 27017 /data/backup"]
        volumeMounts:
        - name: backup-volume
          mountPath: /data/backup
      restartPolicy: OnFailure
      volumes:
      - name: backup-volume
        # PVC나 다른 볼륨 소스를 지정합니다.
        persistentVolumeClaim:
          claimName: mongo-backup-pvc
