apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb
spec:
  type: LoadBalancer         # LoadBalancer 타입으로 변경하여 외부 IP 할당
  ports:
    - port: 27017
      targetPort: 27017      # 컨테이너의 포트를 지정합니다.
  selector:
    app: mongodb