package com.bippobippo.hospital.dto.response.channel;

import com.bippobippo.hospital.entity.channel.Channel;
import com.bippobippo.hospital.entity.channel.ChannelApprovalStatus;
import com.bippobippo.hospital.entity.channel.ChannelSourceType;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

@Getter
@Setter
public class ChannelResponse {
    private Long id;
    private String name;
    private String description;
    private String imageUrl;
    private String channelUri;
    private Integer followerCount;
    private Boolean isAutoGenerated;
    private ChannelSourceType sourceType;
    private Boolean isActive;
    private ChannelApprovalStatus approvalStatus;
    private String rejectionReason;
    private LocalDateTime createdAt;
    private LocalDateTime lastUpdated;

    public static ChannelResponse from(Channel channel) {
        ChannelResponse response = new ChannelResponse();
        response.setId(channel.getId());
        response.setName(channel.getName());
        response.setDescription(channel.getDescription());
        response.setImageUrl(channel.getImageUrl());
        response.setChannelUri(channel.getChannelUri());
        response.setFollowerCount(channel.getFollowerCount());
        response.setIsAutoGenerated(channel.getIsAutoGenerated());
        response.setSourceType(channel.getSourceType());
        response.setIsActive(channel.getIsActive());
        response.setApprovalStatus(channel.getApprovalStatus());
        response.setRejectionReason(channel.getRejectionReason());
        response.setCreatedAt(channel.getCreatedAt());
        response.setLastUpdated(channel.getLastUpdated());
        return response;
    }
} 