package com.bippobippo.hospital.dto.request.channel;

import com.bippobippo.hospital.entity.channel.ChannelSourceType;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class ChannelRequest {
    private String name;
    private String description;
    private String imageUrl;
    private String channelUri;
    private ChannelSourceType sourceType;
    private Boolean isAutoGenerated;
} 